
# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install packages specified in requirements.txt
RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libxslt-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run the scripts sequentially when the container launches
CMD ["sh", "-c", "python generate_cik_yml.py && python extract_financial_info.py --yml_path=output_files/companies_with_cik.yml --output_csv_path=output_files/financial_info.csv"]
