version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./in:/app/in
      - ./out:/app/out
    environment:
      - PYTHONUNBUFFERED=1
    command: sh -c "python generate_cik_yml.py && python extract_financial_info.py --yml_path=out/companies_with_cik.yml --output_csv_path=out/financial_info.csv"
