FROM python:3.11-slim

# Working directory 
WORKDIR /app

COPY . /app

# Install packages specified in requirements.txt
RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libxslt-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

CMD ["sh", "-c", "python generate_cik_yml.py && python extract_financial_info.py --yml_path=out/companies_with_cik.yml --output_csv_path=out/financial_info.csv"]
